### ISSUE TITLE
Build Failing

### ISSUE THREAD

**Issue by kerren** [cfreemoser/netflix_gallery#1]
Hey there,

Something changed with the Github docker action and I see that the builds are failing because of the `git-secret` action. If you update to `v3.1.0` you should be good to go!

**Comment by cfreemoser** [comment]
OMG 😅 I wasn't aware that I actually opened the issue... I am so sorry for the incredibly badly written issue 🙀

Thanks for looking at my pipeline ❤️!

**Comment by kerren** [comment]
Hey no problem :smile:

Haha I think this was me not writing a good issue report :/ but it's all sorted now, thanks for using the action!
